package edu.pitt.cs;
import static org.hamcrest.MatcherAssert.assertThat;
import java.time.Duration;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PittEduTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1TITLE() {
    // Test name: TEST-1-TITLE
    // Step # | name | target | value
    // 1 | open | https://www.pitt.edu/ | 
    driver.get("https://www.pitt.edu/");
    // 2 | assertTitle | Home | University of Pittsburgh | 
    assertThat(driver.getTitle(), is("Home | University of Pittsburgh"));
  }
  @Test
  public void tEST2LOGOEXISTS() {
    // Test name: TEST-2-LOGO-EXISTS
    // Step # | name | target | value
    // 1 | open | https://www.pitt.edu/ | 
    driver.get("https://www.pitt.edu/");
    // 2 | assertElementPresent | xpath=//img[@alt='University of Pittsburgh'] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'University of Pittsburgh\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST3LOGOIMAGE() {
    // Test name: TEST-3-LOGO-IMAGE
    // Step # | name | target | value
    // 1 | open | https://www.pitt.edu/ | 
    driver.get("https://www.pitt.edu/");
    // 2 | storeAttribute | xpath=//img[@alt='University of Pittsburgh']@src | src
    {
      WebElement element = driver.findElement(By.xpath("//img[@alt=\'University of Pittsburgh\']"));
      String attribute = element.getAttribute("src");
      vars.put("src", attribute);
    }
    // 3 | assert | src | /sites/default/files/assets/pitt_shield_white-home.png
    assertEquals(vars.get("src").toString(), "https://www.pitt.edu/sites/default/files/assets/pitt_shield_white-home.png");
  }
  @Test
  public void tEST4SCHOOLSSCI() {
    // Test name: TEST-4-SCHOOLS-SCI
    // Step # | name | target | value
    // 1 | open | https://www.pitt.edu/ | 
    driver.get("https://www.pitt.edu/");
    // 2 | click | css=.nav_content_trigger | 
    driver.findElement(By.cssSelector(".nav_content_trigger")).click();
    // 3 | waitForElementVisible | id=block-pitt-25-edu-collegesschools-2 | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-pitt-25-edu-collegesschools-2")));
    }
    // 4 | assertText | xpath=//nav[@id='block-pitt-25-edu-collegesschools-2']/ul/li[3] | Computing & Information
    assertThat(driver.findElement(By.xpath("//nav[@id=\'block-pitt-25-edu-collegesschools-2\']/ul/li[3]")).getText(), is("Computing & Information"));
  }
  @Test
  public void tEST5SCHOOLSCOUNT() {
    // Test name: TEST-5-SCHOOLS-COUNT
    // Step # | name | target | value
    // 1 | open | https://www.pitt.edu/ | 
    driver.get("https://www.pitt.edu/");
    // 2 | click | css=.nav_content_trigger | 
    driver.findElement(By.cssSelector(".nav_content_trigger")).click();
    // 3 | waitForElementVisible | id=block-pitt-25-edu-collegesschools-2 | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-pitt-25-edu-collegesschools-2")));
    }
    // 4 | assertElementPresent | xpath=//nav[@id='block-pitt-25-edu-collegesschools-2']/ul/li[16] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//nav[@id=\'block-pitt-25-edu-collegesschools-2\']/ul/li[16]"));
      assert(elements.size() > 0);
    }
    // 5 | assertElementNotPresent | xpath=//nav[@id='block-pitt-25-edu-collegesschools-2']/ul/li[17] | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//nav[@id=\'block-pitt-25-edu-collegesschools-2\']/ul/li[17]"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void tEST6SEARCHCSC() {
    // Test name: TEST-6-SEARCH-CSC
    // Step # | name | target | value
    // 1 | open | https://www.pitt.edu/ | 
    driver.get("https://www.pitt.edu/");
    // 2 | click | css=.navbar-search | 
    driver.findElement(By.cssSelector(".navbar-search")).click();
    // 3 | waitForElementEditable | id=edit-keys--2 | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.elementToBeClickable(By.id("edit-keys--2")));
    }
    // 4 | click | id=edit-keys--2 | 
    driver.findElement(By.id("edit-keys--2")).click();
    // 5 | type | id=edit-keys--2 | computer science club
    driver.findElement(By.id("edit-keys--2")).sendKeys("computer science club");
    // 6 | click | css=.button | 
    driver.findElement(By.cssSelector(".button")).click();
    // 7 | waitForElementVisible | css=.gsc-expansionArea | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".gsc-expansionArea")));
    }
    // 8 | assertElementPresent | linkText=Student Organization Spotlight: Computer Science Club (CSC) | 
    {
      List<WebElement> elements = driver.findElements(By.linkText("Student Organization Spotlight: Computer Science Club (CSC)"));
      assert(elements.size() > 0);
    }
  }
}
